version: '3.8'

services:
  asinu-backend:
    build: .
    container_name: asinu-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - asinu_net
    restart: unless-stopped

networks:
  asinu_net:
    external: true
